modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v3"

[[mods]]
modId="embeddiumextras"
version="${file.jarVersion}"
displayName="Embeddium Extras"
credits="TeamDeusVult, TexTrue, LocalizedMC"
authors="Team Potato"
description='''
Adds Extra Settings to Embeddium.
'''

[[dependencies.embeddiumextras]]
modId="embeddium"
mandatory=true
versionRange="[0.1.14+mc1.16.5,)"
ordering="NONE"
side="CLIENT"