modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-2.1"

[[mods]]
modId="magnesium_extras"
version="${file.jarVersion}"
displayName="Embeddium Extras"
credits="TeamDeusVult, TexTrue, LocalizedMC"
authors="Team Potato"
description='''
Adds Extra Settings to Embeddium.
'''

[[dependencies.magnesium_extras]]
modId="embeddium"
mandatory=true
versionRange="[0.1.14+mc1.16.5,)"
ordering="NONE"
side="BOTH"