modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GPL-v3"

[[mods]]
modId = "embeddiumextras"
version = "${version}"
displayName = "EmbeddiumExtras"
authors = "Kall"
description = '''
'''
#logoFile = ""